name: My Workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: nix
        run: |
          curl https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-shell ci.nix --run 'npm run ci'
          nix-build -j 100
          result/bin/update-prefetch test/fetch-url.nix
